#!/usr/bin/env python3
"""
Script: This script uses the list generated by get_variants_by_vendor.py to update the shipping profile for the variants in bulk.
        
Version: 1.0.0

Purpose: 
    - To bulk update the shipping profile for the variants in Shopify using the GraphQL API.  
        Shopify does not have a bulk update for shipping profiles, so we will need to update each variant individually.

Process is as follows:
    - Get the list of variants for a given vendor from the output of get_variants_by_vendor.py.
    - For each variant, update the shipping profile using the GraphQL API.
    - Log the results of the updates.

--------------- DEV NOTES ---------------
- Attempt to run the update in an asynchronous manner to speed up the process.
- Being on Shopify plus nets us a large number of calls, let's use it to our advantage and run the updates in parallel.
- May make a parent script to run the get_variants_by_vendor.py and update_shipping_profile.py in sequence to make it easier to use for non-technical users.
- Potentially add as an app directly on Shopify Admin page.
-----------------------------------------

Requirements:
    - pip install -r requirements.txt

Example:
    - update_shipping_profile.py --vendor "Vendor Name" --shipping_profile_id "Shipping Profile ID"
"""

# ------------ Imports ----------------
from utils import email_errors, email_vars
from dotenv import load_dotenv
from typing import List, Dict, Any, Set, Optional
import asyncio
import aiohttp
import json
import os
# -------------------------------------

# ---------- Constants/Variables ----------------
DEBUG = False
# -----------------------------------------------


def read_json(file_path) -> List:
    """Function to read a JSON file and return the contents as a list of ALL variant ID's.
        This list will be condensed down to batches of 250 variant ID's by the build_variant_list function.
    Args:
        file_path (str): The path to the JSON file to read.
        """
    # Attempt to read the JSON file from file_path and convert to list
    try:
        with open(file_path, 'r') as json_file:
            json_list = []
            data = json.load(json_file)
            for key in data.keys():
                json_list.append(key)
            return json_list

    # Return error messages based on type of exception.
    except FileNotFoundError:
        print(
            f'Error: File not found in path: {file_path}.  Please verify that file exists and try again.')
    except json.JSONDecodeError as err_json:
        print(f'Error decoding JSON file: {err_json}')


def build_variant_list(json_list, batch_size) -> List:
    """Read list of JSON keys and build a list of 250 records to be used by the GraphQL call.
    Args:
        json_list (List): Master list of all variant ID's provided by read_json function.

    """
    # Initialize list to return and i for index to iterate through list
    variant_list = []
    i = 0
    while i < batch_size:
        print(
            f'Record at Index: {i} -- Value: {json_list[i]} to be added to batch')

        variant_list.append([json_list[i]])
        json_list.pop([i])
        i += 1

    return variant_list
    pass


def make_graphql_req(profile_id, variants=[], method=None):
    """Function to make the GraphQL call to Shopify.  
        In this case it will use the deliveryProfileUpdate mutation, schema version 2025-10.
    Args:
    """
    query = """
    mutation deliveryProfileUpdate($id: ID!, $profile: DeliveryProfileInput!) {
        deliveryProfileUpdate(id: $id, profile: $profile) {
            profile {
            id
                    name
                    productVariantsCount
                    {
                        count
                    }
            }
            userErrors {
            field
            message
            }
        }
        }
    """

    variant_method = 'variantsToAssociate'
    if method == 'DELETE':
        variant_method = 'variantsToDissociate'

    variables = {
        'id': profile_id,
        variant_method: variants
    }

    pass


def main():
    pass


if __name__ == '__main__':
    main()
