#!/usr/bin/env python3
"""
Script: This script uses the list generated by get_variants_by_vendor.py to update the shipping profile for the variants in bulk.
        
Version: 1.0.0

Purpose: 
    - To bulk update the shipping profile for the variants in Shopify using the GraphQL API.  
        Shopify does not have a bulk update for shipping profiles, so we will need to update each variant individually.

Process is as follows:
    - Get the list of variants for a given vendor from the output of get_variants_by_vendor.py.
    - For each variant, update the shipping profile using the GraphQL API.
    - Log the results of the updates.

--------------- DEV NOTES ---------------
- Attempt to run the update in an asynchronous manner to speed up the process.
- Being on Shopify plus nets us a large number of calls, let's use it to our advantage and run the updates in parallel.
- May make a parent script to run the get_variants_by_vendor.py and update_shipping_profile.py in sequence to make it easier to use for non-technical users.
- Potentially add as an app directly on Shopify Admin page.
-----------------------------------------

Requirements:
    - pip install -r requirements.txt

Example:
    - update_shipping_profile.py --vendor "Vendor Name" --shipping_profile_id "Shipping Profile ID"
"""


# ---------- Constants/Variables ----------------
DEBUG = False
# -----------------------------------------------


def main():
    pass


if __name__ == '__main__':
    main()
